Remove fr.wikisource due to bug
fr.wikisource gives an error (see below) and blocks the wikis after it. Temporarily remove fr.wikisource while investigating the bug.

WARNING: Http response status 503
WARNING: Non-JSON response received from server wikisource:fr; the server may be down.
Set gaplimit = ['100']
WARNING: Waiting 5 seconds before retrying.
WARNING: Http response status 500
ERROR: Traceback (most recent call last):
  File "/shared/pywikipedia/core/pywikibot/data/api.py", line 517, in submit
    headers=headers, body=body)
  File "/shared/pywikipedia/core/pywikibot/tools.py", line 367, in wrapper
    return method(*__args, **__kw)
  File "/shared/pywikipedia/core/pywikibot/comms/http.py", line 278, in request
    return request.data[1].decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd9 in position 2528: ordinal not in range(128)